[workspace]

members = [
    "sim-validator-assignment"
]

[profile.dev.package]
# Optimizing `insta` and `similar` is recommended for faster runs.
# https://insta.rs/docs/quickstart/#optional-faster-runs
insta.opt-level = 3
similar.opt-level = 3
